// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feeds_users.sql

package database

import (
	"context"
	"database/sql"
)

const followFeed = `-- name: FollowFeed :one
INSERT INTO feeds_users (id, created_at, updated_at, feed_id, user_id)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, created_at, updated_at, feed_id, user_id
`

type FollowFeedParams struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	FeedID    string
	UserID    string
}

func (q *Queries) FollowFeed(ctx context.Context, arg FollowFeedParams) (FeedsUser, error) {
	row := q.db.QueryRowContext(ctx, followFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedID,
		arg.UserID,
	)
	var i FeedsUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
		&i.UserID,
	)
	return i, err
}
